
server:
    host: 127.0.0.1
    port: 8888
    name: payroll_server
    database:
        host: mysql.dev.zgcszkw.com
        username: root
        passwd: AppStore@123
        port: 3306
        showsql: true
